### ISSUE TITLE
Blur operation does not Blur drawn elements

### ISSUE THREAD

**Issue by lucastarche** [RealKC/kcshot#3]
For instance, if blurring over an ellipse, the colour which should be present is not there. 
Example: 
![image](https://user-images.githubusercontent.com/43870496/139062385-459b9039-3a3f-4c4e-8e47-db9e68b7142d.png)

**Comment by RealKC** [comment]
With #7, this issue is a lot more visible and more easily replicable.

I still don't know how this would be fixed though.
